fix: updated yml file

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -34,14 +34,14 @@ jobs:
           
           # echo "MONGO_DB_TEST=mongodb+srv://parthirache8:ufPeWVX7HabgpyVh@cluster0.eo9svyz.mongodb.net/test" >> .env
 
-      # - name: Run test
-      #   working-directory: ./Backend
-      #   run: |
-      #     npm test
-      #     if [ $? -ne 0 ]; then
-      #       echo "Tests failed, exiting."
-      #       exit 1
-      #     fi
+      - name: Run test
+        working-directory: ./Backend
+        run: |
+          npm test
+          if [ $? -ne 0 ]; then
+            echo "Tests failed, exiting."
+            exit 1
+          fi
 
       - name: Build Docker Image for Server
         working-directory: ./backend2
